table dim_date
	lineageTag: 8c71f9eb-bc5e-4dde-a14f-b65e9df5a9fb

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f44c774-b2e9-4634-b457-3c7a84114240
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 2692bbb9-8809-42e4-a155-c533071374f2
			defaultHierarchy: LocalDateTable_e47f835f-83a5-4daa-bf05-6d7051c72da8.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsWeekday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1ce8e20a-9438-4644-a35e-dcd737afeb49
		summarizeBy: none
		sourceColumn: IsWeekday

		annotation SummarizationSetBy = Automatic

	column YearMonth = FORMAT([Date], "YYYY-MM")
		lineageTag: ab6820be-9304-4661-acd7-24dd835d214f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MonthShortName = FORMAT ( 'dim_date'[Date], "MMM" ) & FORMAT( 'dim_date'[Date], "YY")
		lineageTag: 4037a564-5797-42d2-a2c8-a60679db8d80
		summarizeBy: none
		sortByColumn: YearMonth

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Festival
		dataType: string
		lineageTag: 89e58d69-6c13-41f6-a4b9-7879f7b1e14d
		summarizeBy: none
		sourceColumn: Festival

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b1d45775-c727-4698-861c-67bb4966f967
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 8e92c7fc-c749-45d1-9d47-0f8a89aee76c
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: f6ffc3e8-305f-4b6d-8d8b-a14cfc858ec3
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: c96c65b7-32a3-4309-b208-88239b7304b5
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column YearWeekIndex
		dataType: int64
		formatString: 0
		lineageTag: 17ccbbdb-328a-474d-b585-4d49b0589be9
		summarizeBy: sum
		sourceColumn: YearWeekIndex

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: f6ec9ee1-16de-4429-ba9e-79bed4a0116a
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: f439f6ca-9815-4066-b346-ef9d5908a8d2
		summarizeBy: none
		sourceColumn: MonthShort

		annotation SummarizationSetBy = Automatic

	column 'Holiday Type'
		dataType: string
		lineageTag: 211b4c05-f33c-439e-9719-00d52a0d5007
		summarizeBy: none
		sourceColumn: Holiday Type

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		queryGroup: Load
		source =
				let
				    StartDate = StartDate,
				    EndDate = EndDate,
				
				    DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    DateTable_Typed = Table.TransformColumnTypes(DateTable, {{"Date", type date}}),
				
				    AddYear = Table.AddColumn(DateTable_Typed, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddDay = Table.AddColumn(AddMonth, "Day", each Date.DayOfWeek([Date]), Int64.Type),
				
				    AddWeek = Table.AddColumn(AddDay, "Week", each
				        let
				            daysBetween = Duration.Days([Date] - StartDate),
				            weekNumber = Number.IntegerDivide(daysBetween, 7) + 1,
				            weekStart = Date.AddDays(StartDate, (weekNumber - 1) * 7),
				            weekEnd = Date.AddDays(weekStart, 6),
				            monthAbbr = Date.ToText(weekStart, "MMM", "en-US")
				        in
				            "W" & Text.From(weekNumber) & " " & monthAbbr & " " & Text.From(Date.Day(weekStart)) & "-" & Text.From(Date.Day(weekEnd)),
				        type text),
				    AddWeekIndex = Table.AddColumn(AddWeek, "YearWeekIndex",
				        each Number.IntegerDivide(Duration.Days([Date] - StartDate), 7) + 1, Int64.Type),
				
				    AddIsWeekday = Table.AddColumn(AddWeekIndex, "IsWeekday", each Date.DayOfWeek([Date], Day.Monday) < 5, type logical),
				    AddMonthName = Table.AddColumn(AddIsWeekday, "Month Name", each Date.ToText([Date], "MMMM", "en-US"), type text),
				    AddMonthshort = Table.AddColumn(AddMonthName, "MonthShort", each Date.ToText([Date], "MMMyy", "en-US"), type text),
				    MergeHolidays = Table.NestedJoin(AddMonthshort, {"Date"}, Holiday, {"Date"}, "Google Holiday", JoinKind.LeftOuter),
				    ExpandHolidays = Table.ExpandTableColumn(MergeHolidays, "Google Holiday", {"Festival", "Type"}, {"Festival", "Holiday Type"})
				in
				    ExpandHolidays

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

